src/keenon/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'account'

urlpatterns = [
	path('', views.account, name="account"),
	path('details/', views.account_details, name = "account-details"),
	path('addproductform/', views.addproduct, name = "addproductform"),
	path('updateform/', views.profile, name = "updateform"),
	path('register/', views.registerPage, name='register'),
	path('login/', views.loginPage, name='login'),
	path('logout/', views.logoutUser, name='logout'),

	path('reset_password/', auth_views.PasswordResetView.as_view(
		email_template_name="account/password_reset_email.html",
		success_url=reverse_lazy("account:password_reset_done"),
		template_name = "account/password_reset.html"), name="reset_passwod"),

	path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
		template_name="account/password_reset_sent.html"), name="password_reset_done"),

	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
		success_url=reverse_lazy("account:password_reset_complete"),
		template_name="account/password_reset_form.html"), name="password_reset_confirm"),
	
	path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
		template_name="account/password_reset_done.html"), name="password_reset_complete"),
]

src/keenon/keenon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('account/',include('account.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/keenon/store/urls.py
from django.urls import path

from . import views

urlpatterns = [
        #Leave as empty string for base url
    path('', views.home, name="home"),
	path('store/', views.store, name="store"),
	path('cart/', views.cart, name="cart"),
	path('checkout/', views.checkout, name="checkout"),
	path('update_item/', views.updateItem, name="update_item"),
	path('process_order/', views.processOrder, name="process_order"),
	path('product_details/<int:id>', views.product_details, name="product_details"),
]

src/keenon/store/models.py
from django.db import models
from django.contrib.auth.models import User

from account.models import Customer
# Create your models here.

class Address(models.Model):
	user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True)
	country =models.CharField(max_length= 200, null=True) 
	city =models.CharField(max_length= 200, null=True)
	town =models.CharField(max_length= 200, null=True) 
	aveSt = models.CharField(max_length= 200, null=True) 
	apartmentNo = models.CharField(max_length= 200, null=True) 
	zipCode = models.CharField(max_length= 200, null=True) 
		
	def _str_(self):
		return self.country + " " + self.city + " " + self.town + " " +self.aveSt + " " + self.apartmentNo + " " + self.zipCode		

class Product(models.Model):
	id = models.AutoField
	customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True, related_name="product_c")
	name = models.CharField(max_length=200, null=True)
	price= models.FloatField()
	digital = models.BooleanField(default=False, null=True, blank=False)
	image = models.ImageField(null=True, blank=True)
	quantity = models.IntegerField(default=0, null=True, blank=True)
	description =models.CharField(default="default", max_length=2000, null=False)
	def _str_(self):
		return self.name
	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url

class Order(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
	data_ordered = models.DateTimeField(auto_now_add=True)
	complete = models.BooleanField(default=False, null=True, blank=False)
	transaction_id = models.CharField(max_length=100, null=True)

	def _str_(self):
		return str(self.id)
	@property
	def get_cart_total(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])
		return total

	@property
	def get_cart_items(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.quantity for item in orderitems])
		return total

class OrderItem(models.Model):
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
	quantity = models.IntegerField(default=0, null=True, blank=True)
	date_added = models.DateTimeField(auto_now_add=True)

	@property
	def get_total(self):
		total = self.product.price *self.quantity
		return total


class ShippingAddress(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
	address = models.CharField(max_length=200, null=False)
	city = models.CharField(max_length=200, null=False)
	state = models.CharField(max_length=200, null=False)
	zipcode = models.CharField(max_length=200, null=False)
	date_added = models.DateTimeField(auto_now_add=True)

	def _str_(self):
		return self.address

src/keenon/store/views.py
from django.shortcuts import render
from .models import Product, Order
from account.views import account_details, login
from account.models import Customer
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib import messages
import json
import datetime
from .models import *
from .utils import cookieCart, cartData, guestOrder
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.template.loader import get_template
# Create your views here.

def product_details(request):
	products = Product.objects.all()
	context = {'products':products}
	return render(request, 'store/product-details.html', context)

def home(request):
	products = Product.objects.all().order_by('-id')[:6]
	context = {'products':products}
	return render(request, 'store/index.html', context)

def store(request):
	data = cartData(request)

	cartItems = data['cartItems']
	order = data['order']
	items = data['items']

	products = Product.objects.all()
	context = {'products': products, 'cartItems': cartItems}
	return render(request, 'store/store.html', context)

def cart(request):

	if request.user.is_authenticated:
		customer = request.user.customer
		order, created = Order.objects.get_or_create(customer=customer, complete=False)
		items = order.orderitem_set.all()
		cartItems = order.get_cart_items
	else:
		return redirect( "account:login")
		#Create empty cart for now for non-logged in user

	context = {'items':items, 'order':order, 'cartItems':cartItems}
	return render(request, 'store/cart.html', context)

def checkout(request):
	if request.user.is_authenticated:
		customer = request.user.customer
		order, created = Order.objects.get_or_create(customer=customer, complete=False)
		items = order.orderitem_set.all()
		cartItems = order.get_cart_items
		if (request.user.address.country==None or request.user.address.city==None or request.user.address.town==None or request.user.address.aveSt==None or request.user.address.apartmentNo==None):
			messages.warning(request, 'You need to update your address information from Account Page->Edit User Information')
			context = {'messages':messages,'items':items, 'order':order, 'cartItems':cartItems}
			return redirect('cart')
		address=request.user.address

	else:
		#Create empty cart for now for non-logged in user
		items = []
		order = {'get_cart_total':0, 'get_cart_items':0, 'shipping':False}
		cartItems = order['get_cart_items']
		address = None
	context = {'items':items, 'order':order, 'cartItems':cartItems,'address':address}
	return render(request, 'store/checkout.html', context)
 
def updateItem(request):
	data = json.loads(request.body)
	productId = data['productId']
	action = data['action']
	print('Action:', action)
	print('Product:', productId)

	customer = request.user.customer
	product = Product.objects.get(id=productId)
	print("HERE")
	order, created = Order.objects.get_or_create(customer=customer, complete=False)

	orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

	if action == 'add':
		if not(orderItem.quantity+1 > product.quantity):
			orderItem.quantity = (orderItem.quantity + 1)
			product.quantity-=1
	elif action == 'remove':
		orderItem.quantity = (orderItem.quantity - 1)
		product.quantity+=1

	product.save()
	orderItem.save()

	if orderItem.quantity <= 0:
		orderItem.delete()

	return JsonResponse('Item was added', safe=False)

def processOrder(request):
	print("HERE2")
	transaction_id = datetime.datetime.now().timestamp()
	data = json.loads(request.body)

	if request.user.is_authenticated:
		customer = request.user.customer
		order, created = Order.objects.get_or_create(customer=customer, complete=False)
	else:
		customer, order = guestOrder(request, data)

	total = float(data['form']['total'])
	order.transaction_id = transaction_id

	if total == order.get_cart_total:
		order.complete = True
	order.save()

	if order.shipping == True:
		ShippingAddress.objects.create(
		customer=customer,
		order=order,
		address=data['shipping']['address'],
		city=data['shipping']['city'],
		state=data['shipping']['state'],
		zipcode=data['shipping']['zipcode'],
		)

	return JsonResponse('Payment submitted..', safe=False)
def product_details(request,id):
	context = {}
	product = get_object_or_404(Product,id = id)
	context = {'product': product, 'id': id}
	print(product.quantity)
	return render(request, "store/product-details.html",context)


# these are all just for GET request, POST tests will be 
# added soon

src/keenon/store/templates/store/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale = 1.0">
	<title>Keen-on | CSE343</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
	{% block forHead %}
        replace me
    {% endblock %}
    <script type="text/javascript">
		var user = '{{request.user}}'

		function getToken(name) {
		    var cookieValue = null;
		    if (document.cookie && document.cookie !== '') {
		        var cookies = document.cookie.split(';');
		        for (var i = 0; i < cookies.length; i++) {
		            var cookie = cookies[i].trim();
		            // Does this cookie string begin with the name we want?
		            if (cookie.substring(0, name.length + 1) === (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}
		var csrftoken = getToken('csrftoken')

		function getCookie(name) {
		    // Split cookie string and get all individual name=value pairs in an array
		    var cookieArr = document.cookie.split(";");

		    // Loop through the array elements
		    for(var i = 0; i < cookieArr.length; i++) {
		        var cookiePair = cookieArr[i].split("=");

		        /* Removing whitespace at the beginning of the cookie name
		        and compare it with the given string */
		        if(name == cookiePair[0].trim()) {
		            // Decode the cookie value and return
		            return decodeURIComponent(cookiePair[1]);
		        }
		    }

		    // Return null if not found
		    return null;
		}
		var cart = JSON.parse(getCookie('cart'))

		if (cart == undefined){
			cart = {}
			console.log('Cart Created!', cart)
			document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
		}
		console.log('Cart:', cart)

	</script>
</head>
<body>
   {% block content %}


            {% endblock content %}


	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
</body>
</html>

src/keenon/store/templates/store/cart.html
<!DOCTYPE html>
{% extends 'store/base.html' %}
{% load static %}

{% block forHead %}
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/checkout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}">
{% endblock %}

{% block content %}
<div style = "background-color:#DDDDE0;">
<div style = "background-color: #00ff00;">
    {% include "store/navbar.html" %}
    <br>
    <br>
    <br>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="col-lg-12">
			<div class="col-lg-12">
				<div class="col-lg-12">
					<div class="col-lg-12">
		<div class="box-element">

			<a  class="btn btn-outline-dark" href="{% url 'store' %}">&#x2190; Continue Shopping</a>

			<br>
			<br>
			<table class="table">
				<tr>
					<th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
					<th><h5>Total:<strong> ₺{{order.get_cart_total|floatformat:2}}</strong></h5></th>
					<th>
						<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'checkout' %}">Checkout</a>
					</th>
					{% if messages %}
						<ul>
						   {% for message in messages %}
							   <li>{{ message }}</li>
						   {% endfor %}
						</ul>
					{% endif %}
				</tr>
			</table>

		</div>

		<br>
		<div class="box-element" style = "background-color:white">
			<div class="cart-row">
				<div style="flex:2"></div>
				<div style="flex:2"><strong>Item</strong></div>
				<div style="flex:1"><strong>Price</strong></div>
				<div style="flex:1"><strong>Quantity</strong></div>
				<div style="flex:1"><strong>Total</strong></div>
			</div>


				<div class="col-lg-12">

				<div style = "background-color:white;">
			{%for item in items %}


			<div class="cart-row">
				<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
				<div style="flex:2"><p>{{item.product.name}}</p></div>
				<div style="flex:1"><p>₺{{item.product.price|floatformat:2}}</p></div>
				<div style="flex:1">
					<p class="quantity">x{{item.quantity}}</p>
					<div class="quantity">
						<img data-product={{item.product.id}} data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">

						<img data-product={{item.product.id}} data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
					</div>
				</div>
				<div style="flex:1"><p>₺{{item.get_total}}</p></div>
				</div>

			{%endfor%}
			</div>
		</div>
	</div>
	</div>
	</div>
		</div>
		</div>
		</div>

	</div>
	<br>
	 <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
	  <br>
    <br>
    <br>
    <br>
</div>
<div class="footer">
	<div class="row">
		<div class="col-5">
			<ul>
				<li><h4>Baran Hasan BOZDUMAN</h4></li>
					<div class="img_link">
						<a href="https://github.com/bhbduman" target="blank">
							<img src="{% static 'images/GitHub.png' %}">
							GitHub
						</a><br>
					</div>
			</ul>
		</div>
		<div class="col-5">
			<ul>
				<li><h4>Nevzat SEFEROGLU</h4></li>
					<a href="https://github.com/nevzatseferoglu" target="blank">
						<div class="img_link">
							<img src="{% static 'images/GitHub.png' %}">
							GitHub
						</div>
					</a>
			</ul>
		</div>
		<div class="col-5">
			<ul>
				<li><h4>Ceren GUMUS</h4></li>
					<a href="https://github.com/cerengumus" target="blank">
						<div class="img_link">
							<img src="{% static 'images/GitHub.png' %}">
							GitHub
						</div>
					</a>

			</ul>
		</div>
		<div class="col-5">
			<ul>
				<li><h4>Ali Bahar</h4></li>
					<a href="https://github.com/alibhr" target="blank">
						<div class="img_link">
							<img src="{% static 'images/GitHub.png' %}">
							GitHub
						</div>
					</a><br>
			</ul>
		</div>
		<div class="col-5">
			<ul>
				<li><h4>iletisim Bilgileri</h4></li>
				<li>Gebze Teknik Universitesi<h4>
                    <li>+9054623235642<h4>
					<a href="https://github.com/SoftEngProjects-RapidSoft/Keen-On" target="blank">
						<div class="img_link">
							<img src="{% static 'images/GitHub.png' %}">
							GitHub
						</div>
					</a><br>
				</h4></li>
			</ul>
		</div>
	</div>
</div>
{% endblock %}

src/keenon/store/templates/store/checkout.html
{% extends 'store/base.html' %}
{% load static %}

{% block forHead %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/payment.css' %}">
{% endblock %}

{% block content %}



<div style = "background-color: #00ff00;">

<div>
    {% include "store/navbar.html" %}
    <br>
    <br>
    <br>
</div>
</div>
<br>
<div style = "background-color: #DDDDE0;">
<div class="row">
  <div class="col-50">
      <div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'cart' %}"> &#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p> ₺{{item.product.price|floatformat:2}}</p></div>
					<div style="flex:1"><p>x{{item.quantity}}</p></div>
				</div>
				{% endfor %}
				<h5>Items:   {{order.get_cart_items}}</h5>
				<h5>Total:    ₺{{order.get_cart_total|floatformat:2}}</h5>
			</div>
		</div>
</div>
<div class="col-75">
      <div class="col-lg-6">
			<div class="box-element">
				<hr>
				<h3>Shipping Address</h3>
				<hr>
				<h4>Country  	 :{{address.country}}</h4>
				<h4>City 		 :{{address.city}}</h4>
				<h4>Town 	     :{{address.town}}</h4>
				<h4>Avenue/Street:{{address.aveSt}}</h4>
				<h4>Apartment No :{{address.apartmentNo}}</h4>
				<h4>Zip Code     :{{address.zipCode}}</h4>
			</div>
		</div>
</div>
	<div class="col-75">
	<div class="card-body">
          <div class="row">
            <div class="col-md-7">
                <div class="left border">
                    <div class="row"> <span class="header">Payment</span>
                        <div class="icons"> <img src="https://img.icons8.com/color/48/000000/visa.png" /> <img src="https://img.icons8.com/color/48/000000/mastercard-logo.png" /> <img src="https://img.icons8.com/color/48/000000/maestro.png" /> </div>
                    </div>
                    <form> <span>Cardholder's name:</span> <input placeholder="Linda Williams"> <span>Card Number:</span> <input placeholder="0125 6780 4567 9909">
                        <div class="row">
                            <div class="col-4"><span>Expiry date:</span> <input placeholder="YY/MM"> </div>
                            <div class="col-4"><span>CVV:</span> <input id="cvv"> </div>
							 </div>
					</form>
                </div>
            </div>
            <div class="col-md-5">
                <div class="right border">
                    <hr>
                    <div class="row lower">
                        <div class="col text-left">Subtotal</div>
                        <div class="col text-right">₺{{order.get_cart_total|floatformat:2}}</div>
                    </div>
                    <div class="row lower">
                        <div class="col text-left">Delivery</div>
                        <div class="col text-right">Free</div>
                    </div>
                    <div class="row lower">
                        <div class="col text-left"><b>Total to pay</b></div>
                        <div class="col text-right"><b>₺{{order.get_cart_total|floatformat:2}}</b></div>
                    </div>
                    <div class="row lower">
                    </div> <button class="btn">Place order</button>
                    <p class="text-muted text-center">Complimentary Shipping & Returns</p>
                </div>
            </div>
        </div>
    </div>
    <div> </div>
</div>
	</div>
</div>


    </div>
</div>

<div style = "background-color: #DDDDE0;">
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
</div>
</div>
</div>
</div>
<div class="footer">
	<div class="row">
		<div class="col-5">
			<ul>
				<li><h4>Baran Hasan BOZDUMAN</h4></li>
					<div class="img_link">
						<a href="https://github.com/bhbduman" target="blank">
							<img src="{% static 'images/GitHub.png' %}">
							GitHub
						</a><br>
					</div>
			</ul>
		</div>
		<div class="col-5">
			<ul>
				<li><h4>Nevzat SEFEROGLU</h4></li>
					<a href="https://github.com/nevzatseferoglu" target="blank">
						<div class="img_link">
							<img src="{% static 'images/GitHub.png' %}">
							GitHub
						</div>
					</a>
			</ul>
		</div>
		<div class="col-5">
			<ul>
				<li><h4>Ceren GUMUS</h4></li>
					<a href="https://github.com/cerengumus" target="blank">
						<div class="img_link">
							<img src="{% static 'images/GitHub.png' %}">
							GitHub
						</div>
					</a>

			</ul>
		</div>
		<div class="col-5">
			<ul>
				<li><h4>Ali Bahar</h4></li>
					<a href="https://github.com/alibhr" target="blank">
						<div class="img_link">
							<img src="{% static 'images/GitHub.png' %}">
							GitHub
						</div>
					</a><br>
			</ul>
		</div>
		<div class="col-5">
			<ul>
				<li><h4>iletisim Bilgileri</h4></li>
				<li>Gebze Teknik Universitesi<h4>
                    <li>+9054623235642<h4>
					<a href="https://github.com/SoftEngProjects-RapidSoft/Keen-On" target="blank">
						<div class="img_link">
							<img src="{% static 'images/GitHub.png' %}">
							GitHub
						</div>
					</a><br>
				</h4></li>
			</ul>
		</div>
	</div>
</div>
</div>
</html>
<script type="text/javascript">
		var shipping = '{{order.shipping}}'
		var total = '{{order.get_cart_total|floatformat:2}}'

		if (shipping == 'False'){
		 	document.getElementById('shipping-info').innerHTML = ''
		}

		if (user != 'AnonymousUser'){
		 	document.getElementById('user-info').innerHTML = ''
		 }

		if (shipping == 'False' && user != 'AnonymousUser'){
			//Hide entire form if user is logged in and shipping is false
				document.getElementById('form-wrapper').classList.add("hidden");
				//Show payment if logged in user wants to buy an item that does not require shipping
			    document.getElementById('payment-info').classList.remove("hidden");
		}

		var form = document.getElementById('form')
		form.addEventListener('submit', function(e){
	    	e.preventDefault()
	    	console.log('Form Submitted...')
	    	document.getElementById('form-button').classList.add("hidden");
	    	document.getElementById('payment-info').classList.remove("hidden");
	    })

	    document.getElementById('make-payment').addEventListener('click', function(e){
	    	submitFormData()
	    })

	    function submitFormData(){
	    	console.log('Payment button clicked')

	    	var userFormData = {
				'name':null,
				'email':null,
				'total':total,
			}

			var shippingInfo = {
				'address':null,
				'city':null,
				'state':null,
				'zipcode':null,
			}

			if (shipping != 'False'){
	    		shippingInfo.address = form.address.value
		    	shippingInfo.city = form.city.value
		    	shippingInfo.state = form.state.value
		    	shippingInfo.zipcode = form.zipcode.value
	    	}

	    	if (user == 'AnonymousUser'){
	    		userFormData.name = form.name.value
	    		userFormData.email = form.email.value
	    	}

	    	console.log('Shipping Info:', shippingInfo)
	    	console.log('User Info:', userFormData)

	    	var url = "/process_order/"
	    	fetch(url, {
	    		method:'POST',
	    		headers:{
	    			'Content-Type':'applicaiton/json',
	    			'X-CSRFToken':csrftoken,
	    		},
	    		body:JSON.stringify({'form':userFormData, 'shipping':shippingInfo}),

	    	})
	    	.then((response) => response.json())
	    	.then((data) => {
				  console.log('Success:', data);
				  alert('Transaction completed');
				  window.location.href = "{% url 'store' %}"

				})
	    }
	</script>
{% endblock content %}

src/keenon/store/templates/store/navbar.html
{% load static %}

<div class="navbar">
    <div class="logo">
        <a href="{% url 'home' %}"><img src="{% static 'images/logo.png' %}" width="125px"></a>
    </div>
	<nav>
		<ul id="MenuItems">
			<li><a href="{% url 'home' %}">Home</a></li>
			<li><a href="{% url 'store' %}">Products</a></li>
		<!--	<li><a href="">About</a></li> -->
			<li><a href="{% url 'account:account' %}">Account</a></li>
            <li>
                 <a href = "{% url 'cart' %}">
                    <img id='cart-icon' src="{% static 'images/cart.png' %}" width="25px"></a>
                <p id="cart-total">{{cartItems}}</p>


            </li>
		</ul>
	</nav>
	<img src="{% static 'images/menu.png' %}" class="menu-icon" onclick="menutoggle()">
</div>

<script>
	var MenuItems = document.getElementById("MenuItems");
	MenuItems.style.maxHeight = "0px";
	function menutoggle(){
		if(MenuItems.style.maxHeight == "0px"){
			MenuItems.style.maxHeight = "200px"
		}
		else{
			MenuItems.style.maxHeight = "0px"
		}
	}
</script>
	<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>